//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_arac()
        {
            this.tbl_musteri = new HashSet<tbl_musteri>();
        }
    
        public int id { get; set; }
        public string plaka { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string arac_tipi { get; set; }
        public string renk { get; set; }
        public string yil { get; set; }
        public string resim { get; set; }
        public string durum { get; set; }
        public string arac_durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_musteri> tbl_musteri { get; set; }
    }
}
