//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kiralama
    {
        public int id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public string tc { get; set; }
        public string plaka { get; set; }
        public string alis_tarihi { get; set; }
        public string veris_tarihi { get; set; }
        public Nullable<int> ucret { get; set; }
    
        public virtual tbl_musteri tbl_musteri { get; set; }
    }
}
